version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/chat

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: rename config
          command: mv ~/chat/config.dist.js ~/chat/config.js

      - run:
          name: build templates
          command: npx gulp templates

      - run:
          name: stylelint
          command: npm run stylelint

      - run:
          name: eslint
          command: npm run eslint

  deploy:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "84:28:86:5a:6a:bd:0e:1d:d5:aa:bf:0d:f4:fa:4e:86"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -oStrictHostKeyChecking=no -v sysadmin@nikolskiy.me -p 2222 './deploy_slack_chat.sh'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
