version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/chat
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/chat
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Rename config
          command: mv ~/chat/config.dist.js ~/chat/config.js
      - run:
          name: Build templates
          command: npx gulp templates
      - run:
          name: Stylelint
          command: npm run stylelint
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Testing
          command: npm t

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST -p $SSH_PORT "~/deploy_slack_chat.sh"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
